### ISSUE TITLE
UTC time format...?

### ISSUE THREAD

**Issue by rothnd** [netplexflix/New-Season-Soon-for-Kometa#2]
Hi, I'm on macOS trying to play with your scripts and I can't get around the time stamp being in UTC. My system just throws errors saying it doesn't understand UTC. Is there a work-around?

**Comment by netplexflix** [comment]
What's your python version?

**Comment by rothnd** [comment]
v3.8.6

**Comment by netplexflix** [comment]
I think you need 3.9.. (I see I wrote 3.8 in readme..)
Can you upgrade Python and try again?

**Comment by rothnd** [comment]
I will do that and try again at some point thanks!

**Comment by rothnd** [comment]
I believe that (v13.3.2) is doing the trick. nssk.py ran, now running Kometa.

**Comment by rothnd** [comment]
Awesome! Quick question - is there any mechanism for similar with movies? Like a collection generator for movies that will have sequels within xx months or something?

**Comment by rothnd** [comment]
Last one, sorry, where do I handle Kometa ignore_blank_results for this collection?

**Comment by netplexflix** [comment]
Cool. I'll update the readme to mention Python >3.9

There is nothing like this for Movies yet. I'll look into it!

I've never used ignore_blank_results tbh. Are you encountering any issues that would require it?

Btw, I included the functionality of [New Season Soon](https://github.com/netplexflix/New-Season-Soon-for-Kometa) and [Finale Labeler](https://github.com/netplexflix/Finale-Labeler-For-Plex) in a new script: [TV Show Status for Kometa](https://github.com/netplexflix/TV-show-status-for-Kometa)
Future development will be done on that one.

**Comment by rothnd** [comment]
Oook. So this TSSK will supersede the one I’m using (NSSK)?

No issues. Yet. I just know that that collection won’t have Ian’ items in it from time to time but I want the collection to always be visible in the future.

**Comment by netplexflix** [comment]
NSSK should keep working, but yes I integrated its functionality in TSSK so if I develop any further features it will be for that one. I can still apply small fixes to NSSK when needed.

I see. I'll look into it. Let me know if you encounter any issues.

Feel free to join the Discord for further features brainstorming!

**Comment by rothnd** [comment]
I will do that! Transitioning to TSSK now. So what I'm asking about/thinking might look like

```
################################################################################
##########                        NEW SEASON:                         ##########
################################################################################

future_days_new_season: 60
collection_name_new_season: "Sequel Related"
sort_title_new_season: "!!!02 Sequel Related"

collection_order: title.asc
ignore_blank_results: true

backdrop_new_season:
  enable: true
  back_color: "#228B22"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text_new_season:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "NEW SEASON"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"
```

particularly, the ignore and collection_order settings is what I'm wondering about. Thank you for this!
